# Generated by Django 3.2.8 on 2021-10-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdapis', '0002_author_about_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='about_me',
        ),
        migrations.AddField(
            model_name='author',
            name='display_name',
            field=models.CharField(default='Your Display Name', max_length=500),
        ),
        migrations.AddField(
            model_name='author',
            name='profilr_image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
