# Generated by Django 3.2.8 on 2021-10-19 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdapis', '0003_auto_20211019_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='profilr_image',
            new_name='profile_image',
        ),
    ]
