# Generated by Django 3.2.8 on 2021-10-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdapis', '0005_alter_author_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
