# Generated by Django 3.2.8 on 2021-10-19 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sdapis', '0007_alter_author_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='authorID',
            new_name='author_id',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('post_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('source', models.URLField()),
                ('origin', models.URLField()),
                ('description', models.TextField(default='description of the post')),
                ('contentType', models.CharField(default='text/plain', max_length=20)),
                ('content', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('unlisted', models.BooleanField(default=False)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment', models.TextField()),
                ('contentType', models.CharField(default='text/plain', max_length=20)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('comment_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_of_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdapis.post')),
            ],
        ),
    ]
