# Generated by Django 3.2.8 on 2021-10-19 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdapis', '0009_follow_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='display_name',
        ),
    ]
