# Generated by Django 3.2.8 on 2021-10-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdapis', '0010_remove_author_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_of_comment',
            new_name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
