# Generated by Django 3.2.8 on 2021-10-22 04:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdapis', '0011_auto_20211021_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
    ]
