# Generated by Django 3.2.8 on 2021-10-22 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdapis', '0013_post_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_author',
        ),
    ]
