# Generated by Django 3.2.8 on 2021-10-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdapis', '0014_remove_post_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='long_post_id',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
