# Generated by Django 3.2.8 on 2021-10-22 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdapis', '0015_post_long_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='long_post_id',
        ),
    ]
