# Generated by Django 3.2.8 on 2021-10-23 18:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdapis', '0016_remove_post_long_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=40, unique=True)),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None)),
            ],
        ),
    ]
