# Generated by Django 3.2.8 on 2021-10-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdapis', '0017_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Web Tutorial', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'public'), ('FRIEND', 'friend')], default='PUBLIC', max_length=6),
        ),
    ]
