# Generated by Django 3.2.8 on 2021-10-24 02:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sdapis', '0019_auto_20211023_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
