# Generated by Django 3.2.8 on 2021-10-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdapis', '0023_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='author_id',
            field=models.CharField(default='no author', max_length=100),
        ),
    ]
