# Generated by Django 3.2.8 on 2021-10-24 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdapis', '0024_auto_20211023_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_id',
        ),
    ]
