# Generated by Django 3.2.8 on 2021-10-24 04:02

from django.db import migrations, models
import sdapis.models


class Migration(migrations.Migration):

    dependencies = [
        ('sdapis', '0025_remove_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.UUIDField(default=sdapis.models.uuid_hex, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default=sdapis.models.uuid_hex, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
