# Generated by Django 3.2.8 on 2021-10-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdapis', '0027_auto_20211023_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
