# Generated by Django 3.2.8 on 2021-10-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdapis', '0028_auto_20211023_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(null=True),
        ),
    ]
