# Generated by Django 3.2.8 on 2021-11-09 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdapis', '0032_alter_author_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
